### PR TITLE
Add C# code examples

### PR DESCRIPTION
**Pull request by adam-invoiced**
The majority of this PR is to add C# code examples to the API documentation. There are also some minor corrections to other code examples.

### CODE REVIEW

**Comment by jaredtking** [comment]
Also, there should be a .NET example in the Authentication setting to show how to setup the client.

**Comment by adam-invoiced** [comment]
I was having trouble with special characters in the .erb file that defines the tabs. Do you know how to force them in there?

Ah, yes, I'll get the authentication example in there

**Comment by jaredtking** [comment]
I think you can patch `source/layouts/layout.erb` to change the text in the tab

**Comment by jaredtking** [comment]
Actually I was able to put in .NET with no issue. I see how C# could be problematic

**Comment by adam-invoiced** [comment]
Ah ok. I guess commit that? It's still giving me trouble

**Comment by adam-invoiced** [comment]
Ok I was able to get `c#` to work. I'm going off [this](https://github.com/rouge-ruby/rouge/wiki/List-of-supported-languages-and-lexers) which the Slate docs pointed me to. If I enter `.NET` it will display for me but it makes the JSON examples always appear.

**Pull request merged**
